global:
  namespace: default
  name: maskrcnn-32x4-seed41-24e-run2
maskrcnn:
  experiment_group: default
  gpus: 32
  batch_size_per_gpu: 4
  image: armandmcqueen/tensorpack-mask-rcnn:dev-seed_add41_experiment
  train_script: /tensorpack-mask-rcnn/MaskRCNN/train.py
  fp_16: 1
  base_lr: 0.0015
  warmup_lr: 0.000416667
  shared_fs: fsx
  data_fs: fsx
  shared_pvc: tensorpack-fsx
  data_dir: ''
  working_dir: /tensorpack-mask-rcnn
  images_per_epoch: 120000
  lr_epoch_schedule: '[(16, 0.1), (20, 0.01), (24, None)]'
  eval_period_in_epochs: 24
  data_train: '["train2017"]'
  data_val: ("val2017")
  mode_fpn: 'True'
  mode_mask: 'True'
  backbone_norm: FreezeBN
  backbone_weights: pretrained-models/ImageNet-R50-AlignPadding.npz
  predefined_padding: 'False'
  topk_per_image: 'True'
  image_pull_policy: Always
  horovod_cycle_time: '0.5'
  horovod_fusion_threshold: '67108864'
  nccl_socket_ifname: ^lo,docker0
  nccl_min_rings: 8
  nccl_debug: INFO
  bbox_reg_weights: '[10., 10., 5., 5.]'
  result_score_thresh: 0.05
  gpus_per_node: 8

